/**
 * The Lucide icons the page draws. `scripts/build.ts` inlines exactly these
 * from `lucide-static` and fails when one does not exist, so adding a glyph
 * means adding its Lucide name here.
 */
export const ICON_NAMES = [
  "align-left",
  "arrow-down-right",
  "arrow-left-right",
  "arrow-right-left",
  "arrow-up-right",
  "book-open",
  "bot",
  "cake",
  "calendar",
  "chart-column",
  "chevron-down",
  "chevron-up",
  "crosshair",
  "eye",
  "file",
  "files",
  "flag",
  "flame",
  "flask-conical",
  "folder",
  "ghost",
  "git-branch",
  "hash",
  "history",
  "hourglass",
  "indent-increase",
  "info",
  "key-round",
  "languages",
  "layers",
  "moon",
  "package",
  "refresh-cw",
  "repeat",
  "ruler",
  "shield-check",
  "shuffle",
  "snowflake",
  "sparkles",
  "split",
  "sprout",
  "sun-moon",
  "target",
  "text",
  "trash-2",
  "tree-palm",
  "truck",
  "user",
  "user-plus",
  "users",
  "weight",
  "zap",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
